---
title: "Compare BET catches in the WCPFC convention area to catch limits"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(knitr)
library(readxl)
library(tidyverse)
library(countrycode)

source(here::here("scripts", "00_setup.R"))
```

## Catches and Catch Quotas

```{r cars}
catch_dat <- read_csv(file.path(clean_dir, "wcpfc_yearbook_dat_tidy_1950_2018_LL_ONLY.csv"))

quota_dat <- read_csv(file.path(clean_dir, "wcpfc_bet_quota_dat_tidy_2014_2020.csv"))
```

Combine LL catches with quotas by flag state

```{r}
catch_quota_dat <- catch_dat %>%
  dplyr::filter(year >= 2014 & species == "bet") %>%
  group_by(year, gear, flag_iso3, flag_name, species, is_SID) %>%
  summarize(catch = sum(catch, na.rm = T)) %>%
  ungroup() %>%
  left_join(quota_dat %>% dplyr::select(-flag_name, -flag_iso2), by = c("year", "flag_iso3")) %>%
  mutate(quota = case_when(!is.na(quota) ~ quota,
                           !is_SID ~ 2000))
```

Make plots

```{r}
# Wrangle data
catch_quota_facet_plot_dat <- catch_quota_dat %>%
  dplyr::filter(catch > 0) %>%
  mutate(bar_start = (year - min(catch_quota_dat$year)) + 1 - 0.45,
         bar_end = (year - min(catch_quota_dat$year)) + 1 + 0.45) %>%
  mutate(country_fill_color = case_when(is_SID ~ "grey",
                                        TRUE ~ "blue"),
         is_over_quota = ifelse(catch > quota, T, F)) 

# Plot of all countries
catch_quota_facet_plot_by_flag_ALL <- ggplot()+
  geom_bar(data = catch_quota_facet_plot_dat,
           aes(x=as.factor(year), y = catch, fill = country_fill_color), 
           stat = "identity")+
  geom_bar(data = catch_quota_facet_plot_dat %>% dplyr::filter(is_over_quota),
           aes(x=as.factor(year), y = catch, fill = country_fill_color), 
           stat = "identity",
           fill = "red")+
  geom_segment(data = catch_quota_facet_plot_dat,
               aes(x=bar_start, xend=bar_end, y=quota, yend=quota),
               size = 2)+
  facet_wrap(~flag_name, scales = "free_y")+
  theme_classic()+
  labs(x = "Year", y = "Longline BET catch (mt)")+
  scale_fill_manual(values = c("darkslategrey", "grey"))+
  guides(fill = F)

ggsave(file.path(vis_plot_dir, "catch_quota_facet_plot_by_flag_ALL.png"), 
       catch_quota_facet_plot_by_flag_ALL, width = 16, height = 8.5, units = "in")
```

```{r}
# Plot for all non-SID states
catch_quota_facet_plot_by_flag_non_SIDS <- ggplot()+
  geom_bar(data = catch_quota_facet_plot_dat %>% dplyr::filter(!is_SID),
           aes(x=as.factor(year), y = catch, fill = country_fill_color), 
           stat = "identity",
           fill = "darkslategrey")+
  geom_bar(data = catch_quota_facet_plot_dat %>% dplyr::filter(is_over_quota),
           aes(x=as.factor(year), y = catch, fill = country_fill_color), 
           stat = "identity",
           fill = "red")+
  geom_segment(data = catch_quota_facet_plot_dat %>% dplyr::filter(!is_SID),
               aes(x=bar_start, xend=bar_end, y=quota, yend=quota),
               size = 2)+
  facet_wrap(~flag_name, scales = "free_y")+
  theme_classic()+
  labs(x = "Year", y = "Longline BET catch (mt)")+
  guides(fill = F)

ggsave(file.path(vis_plot_dir, "catch_quota_facet_plot_by_flag_non_SIDs.png"), 
       catch_quota_facet_plot_by_flag_non_SIDS, width = 16, height = 8.5, units = "in")
```

```{r}
# Plot for all SID states
catch_quota_facet_plot_by_flag_SIDS <- catch_quota_facet_plot_dat %>%
  dplyr::filter(is_SID) %>%
  ggplot()+
  geom_bar(aes(x=as.factor(year), y = catch), 
           stat = "identity",
           fill = "grey")+
  facet_wrap(~flag_name, scales = "free_y")+
  theme_classic()+
  labs(x = "Year", y = "Longline BET catch (mt)")

ggsave(file.path(vis_plot_dir, "catch_quota_facet_plot_by_flag_SIDs.png"), 
       catch_quota_facet_plot_by_flag_SIDS, width = 16, height = 8.5, units = "in")
```

```{r}
# Plot for top producing states
catch_quota_facet_plot_dat_ranked <- catch_quota_facet_plot_dat %>%
  group_by(flag_name) %>%
  mutate(total_catch = sum(catch, na.rm = T),
         avg_catch = mean(catch, na.rm = T)) %>%
  ungroup() %>%
  mutate(total_rank = dense_rank(desc(total_catch)),
         avg_rank = dense_rank(desc(avg_catch))) %>%
  mutate(flag_name_new = fct_reorder(flag_name, total_rank, min)) %>%
  dplyr::filter(total_rank <= 12)

# Plot of all countries
catch_quota_facet_plot_by_flag_top12 <- ggplot()+
  geom_bar(data = catch_quota_facet_plot_dat_ranked,
           aes(x=as.factor(year), y = catch, fill = country_fill_color), 
           stat = "identity")+
  geom_bar(data = catch_quota_facet_plot_dat_ranked %>% dplyr::filter(is_over_quota),
           aes(x=as.factor(year), y = catch, fill = country_fill_color), 
           stat = "identity",
           fill = "red")+
  geom_segment(data = catch_quota_facet_plot_dat_ranked,
               aes(x=bar_start, xend=bar_end, y=quota, yend=quota),
               size = 2)+
  facet_wrap(~flag_name_new, scales = "free_y")+
  theme_classic()+
  labs(x = "Year", y = "Longline BET catch (mt)")+
  scale_fill_manual(values = c("darkslategrey", "grey"))+
  guides(fill = F)

ggsave(file.path(vis_plot_dir, "catch_quota_facet_plot_by_flag_top12.png"), 
       catch_quota_facet_plot_by_flag_top12, width = 16, height = 8.5, units = "in")
```
